---
title: "MISS Analysis"
subtitle: "Most Influential Set Selection in Practice"
author: "Anonymous"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    code_folding: hide
    theme: flatly
    highlight: tango
---

```{r setup, include=FALSE}
# Knitr options
knitr::opts_chunk$set(
  echo = TRUE,
  message = TRUE,
  warning = TRUE,
  fig.width = 9,
  fig.height = 7
)

# Source all MISS functions
for (f in list.files("../R", "\\.R$", full.names = TRUE)) {
  source(f, local = FALSE)
}

has_haven <- has_package("haven", "Skipping DTA files.")
has_influence <- has_package("influence", "Skipping freedy algorithm.")
has_mass <- has_package("MASS", "Skipping Boston housing data.")
has_robustbase <- has_package("robustbase", "Skipping stats benchmark datasets.")

# Analysis parameters
K_MAX <- 1000L
```

# Introduction

```{r datasets, cache=TRUE, include=FALSE}
datasets <- list(
 wine_data = list(
    data = read.csv("../data/winequality-red.csv"),
    formula = quality ~ fixed.acidity + volatile.acidity + citric.acid +
      residual.sugar + chlorides + free.sulfur.dioxide +
      total.sulfur.dioxide + density + pH + sulphates + alcohol,
    features = c("alcohol", "volatile.acidity", "sulphates", "citric.acid", "density"),
    name = "Wine Quality",
    description = "Red wine quality ratings from physicochemical properties",
    context = "1,599 Portuguese red wines rated 0-10",
    reference = "UCI ML Repository (Cortez et al., 2009)"
  ),
  adult_census = list(
    data = {\() {
      cols <- c("age", "workclass", "fnlwgt", "education", "education_num",
        "marital_status", "occupation", "relationship", "race", "sex",
        "capital_gain", "capital_loss", "hours_per_week", "native_country", "income")
      d <- read.csv("../data/Adult/adult.data", header = FALSE, na.strings = "?", col.names = cols)
      d$income_binary <- as.integer(d$income == " >50K")
      return(na.omit(d))
    }}(),
    formula = income_binary ~ age + education_num + hours_per_week + capital_gain + capital_loss + sex + race + occupation,
    features = c("age", "education_num", "hours_per_week", "capital_gain", "capital_loss", "sex"),
    name = "Adult Income",
    description = "Predict income >$50K from census variables",
    context = "~30K adults; education and hours worked predict high income",
    reference = "UCI ML Repository (Kohavi, 1996)"
  ),
  housing_california = list(
    data = read.csv("../data/housing.csv"),
    formula = median_house_value ~ median_income + housing_median_age +
      total_bedrooms + population + households,
    features = c("median_income", "housing_median_age", "total_bedrooms"),
    name = "California Housing",
    description = "Median house value from 1990 Census block data",
    context = "20,640 California census blocks; income is dominant predictor",
    reference = "Pace & Barry (1997), Kaggle"
  ),
  housing_boston = list(
    data = MASS::Boston,
    formula = medv ~ crim + zn + indus + chas + nox + rm + age + dis + rad + tax + ptratio + black + lstat,
    features = c("lstat", "rm", "crim", "age"),
    name = "Boston Housing",
    description = "Predict median home value from neighborhood features",
    context = "506 Boston census tracts; classic but ethically questionable",
    reference = "Harrison & Rubinfeld (1978)"
  ),
  sparrows = list(
    data = {\() {
      d <- read.delim("../data/SparrowsElphick.txt", sep = "\t")
      return(na.omit(d[, c("wt", "wingcrd", "tarsus", "head", "flatwing", "culmen", "nalospi", "Sex", "Age")]))
    }}(),
    formula = tarsus ~ head + wingcrd + flatwing + culmen + nalospi + wt + Sex + Age,
    features = c("head", "wingcrd", "flatwing"),
    name = "Saltmarsh Sparrow",
    description = "Predict bird tarsus length from morphological measurements",
    context = "Saltmarsh parrow measurements; body dimensions predict tarsus length",
    reference = "Gjerdrum et al., 2008; Zuur et al., 2010"
  ),
  trust = list(
    data = {\() {
      d <- as.data.frame(haven::read_dta("../data/trust_data.dta"))
      na.omit(d[, c("trust_relatives", "ln_export_area", "age", "age2", "male",
        "urban_dum", "education", "occupation", "religion", "living_conditions",
        "district_ethnic_frac", "frac_ethnicity_in_district", "isocode")])
    }}(),
    formula = trust_relatives ~
      ln_export_area + age + age2 + male + urban_dum + factor(education) +
      factor(occupation) + factor(religion) + factor(living_conditions) +
      factor(isocode) + district_ethnic_frac + frac_ethnicity_in_district,
    features = c("ln_export_area"),
    name = "Mistrust",
    description = "Effect of slave trade (exports per area) on modern trust levels",
    context = "~30 countries; tests historical institutions hypothesis",
    reference = "Nunn & Wantchekon (2011)"
  ),
  tsetse = list(
    data = as.data.frame(haven::read_dta("../data/tsetse_data.dta")),
    formula = plow ~ TSI + prop_tropics + meantemp + meanrh + itx + malaria_index + coast + river + lon + abslat + meanalt + SI,
    features = "TSI",
    name = "Tsetse Fly",
    description = "Adoption of plow technology in relation to Tsetse fly suitability (TSI)",
    context = "TSI negatively affects plow adoption due to lack of draft animals",
    reference = "Alsan (2015)"
  ),
  stars = list(
    data = robustbase::starsCYG,
    formula = log.light ~ log.Te,
    features = "log.Te",
    name = "Star Cluster CYG",
    description = "Hertzsprung-Russell diagram of 47 stars in CYG OB1 cluster",
    context = "Classic robust regression example; giant stars deviate from main sequence",
    known_outliers = c(11, 20, 30, 34),
    reference = "Rousseeuw & Leroy (1987)"
  ),
  exam = list(
    data = robustbase::exAM,
    formula = y ~ x,
    features = "x",
    name = "Antille & May Example",
    description = "Artificial dataset for robust regression illustration",
    context = "Constructed example with clear outliers for demonstration",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  animals2 = list(
    data = robustbase::Animals2,
    formula = log(brain) ~ log(body),
    features = "log(body)",
    name = "Animal Brain to Body",
    description = "Brain and body weights for 65 species of land animals",
    context = "Allometric scaling; dinosaurs are outliers to mammalian trend",
    known_outliers = integer(0),
    reference = "Rousseeuw & Leroy (1987)"
  ),
  lactic = list(
    data = robustbase::lactic,
    formula = Y ~ X,
    features = "X",
    name = "Lactic Acid",
    description = "Lactic acid concentration in cheese",
    context = "Simple linear relationship with potential outliers",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  pilot = list(
    data = robustbase::pilot,
    formula = Y ~ X,
    features = "X",
    name = "Plant Data",
    description = "Pilot plant acid content and organic acid",
    context = "Industrial process data with potential outliers",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  telef = list(
    data = robustbase::telef,
    formula = Calls ~ Year,
    features = "Year",
    name = "Telephone Calls",
    description = "Number of telephone calls over years",
    context = "Time series with potential structural breaks",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  stackloss = list(
    data = datasets::stackloss,
    formula = stack.loss ~ Air.Flow + Water.Temp + Acid.Conc.,
    features = c("Air.Flow", "Water.Temp", "Acid.Conc."),
    name = "Stackloss",
    description = "Operational data from a plant for oxidation of ammonia to nitric acid",
    context = "Classic robust regression benchmark with well-documented outliers",
    known_outliers = c(1, 3, 4, 21),
    reference = "Brownlee (1965)"
  ),
  hbk = list(
    data = robustbase::hbk,
    formula = Y ~ X1 + X2 + X3,
    features = c("X1", "X2", "X3"),
    name = "HBK Artificial Data",
    description = "Artificial dataset with 14 bad leverage points in 75 observations",
    context = "Classic masking example; first 14 observations are outliers",
    known_outliers = 1:14,
    reference = "Hawkins, Bradu & Kass (1984)"
  ),
  wood = list(
    data = robustbase::wood,
    formula = y ~ x1 + x2 + x3 + x4 + x5,
    features = c("x1", "x2", "x3", "x4", "x5"),
    name = "Wood Specific Gravity",
    description = "Modified data on wood specific gravity",
    context = "Artificially contaminated dataset for robust regression testing",
    known_outliers = c(4, 6, 8, 19),
    reference = "Draper & Smith (artificially contaminated)"
  ),
  salinity = list(
    data = robustbase::salinity,
    formula = Y ~ X1 + X2 + X3,
    features = c("X1", "X2", "X3"),
    name = "Salinity",
    description = "Salinity data from Pamlico Sound, North Carolina",
    context = "Environmental data with influential observations",
    known_outliers = c(3, 5, 16),
    reference = "Ruppert & Carroll (1980)"
  ),
  phosphor = list(
    data = robustbase::phosphor,
    formula = plant ~ inorg + organic,
    features = c("inorg", "organic"),
    name = "Phosporous Content",
    description = "Phosphorus content in soil and plants",
    context = "Contains a high-leverage point",
    known_outliers = c(17),
    reference = "robustbase package"
  ),
  education = list(
    data = robustbase::education,
    formula = Y ~ X1 + X2 + X3,
    features = c("X1", "X2", "X3"),
    name = "US Education Expenditure",
    description = "Education expenditure data by US states",
    context = "State-level education data with regional variation",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  aircraft = list(
    data = robustbase::aircraft,
    formula = Y ~ X1 + X2 + X3 + X4,
    features = c("X1", "X2", "X3", "X4"),
    name = "Aircraft Data",
    description = "Aircraft data on 23 single-engine aircraft",
    context = "Contains outliers related to unusual aircraft designs",
    known_outliers = c(22, 23),
    reference = "Gray (1985)"
  ),
  airmay = list(
    data = robustbase::airmay,
    formula = Y ~ X1 + X2,
    features = c("X1", "X2"),
    name = "Air Pollution in May",
    description = "Air pollution data for May",
    context = "Environmental monitoring data",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  bushfire = list(
    data = robustbase::bushfire,
    formula = V5 ~ V1 + V2 + V3 + V4,
    features = c("V1", "V2", "V3", "V4"),
    name = "Bushfire Scars in Australia",
    description = "Satellite data from bushfire scars in Australia",
    context = "Pixel-level measurements with contamination from non-fire areas",
    known_outliers = 32:38,
    reference = "Maronna & Yohai"
  ),
  cloud = list(
    data = robustbase::cloud,
    formula = CloudPoint ~ Percentage,
    features = "Percentage",
    name = "Cloud Point",
    description = "Cloud point of a liquid",
    context = "Chemical property measurement",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  condroz = list(
    data = robustbase::condroz,
    formula = Ca ~ pH,
    features = "pH",
    name = "Condroz Soil Chemistry",
    description = "Calcium content in soil samples from Condroz region",
    context = "Soil chemistry with potential measurement outliers",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  heart = list(
    data = robustbase::heart,
    formula = clength ~ height + weight,
    features = c("height", "weight"),
    name = "Heart Catheter",
    description = "Heart catheter data",
    context = "Medical measurements",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  pension = list(
    data = robustbase::pension,
    formula = Reserves ~ Income,
    features = "Income",
    name = "Pension Fund",
    description = "Pension fund data",
    context = "Financial data with potential outliers from unusual funds",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  pulpfiber = list(
    data = robustbase::pulpfiber,
    formula = Y1 ~ X1 + X2 + X3 + X4,
    features = c("X1", "X2", "X3", "X4"),
    name = "Pulp Fiber",
    description = "Pulp fiber and paper properties",
    context = "Industrial process data",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  toxicity = list(
    data = robustbase::toxicity,
    formula = toxicity ~ logKow + pKa + ELUMO + Ecarb + Emet,
    features = c("logKow", "pKa", "ELUMO", "Ecarb", "Emet"),
    name = "Toxicity",
    description = "Toxicity of chemicals to Daphnia magna",
    context = "Chemical structure-activity relationship with potential outliers",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  wagner_growth = list(
    data = robustbase::wagnerGrowth,
    formula = y ~ PA + GPA + HS + GHS,
    features = c("PA", "GPA", "HS", "GHS"),
    name = "Wagner Growth",
    description = "Wagner growth data",
    context = "Growth curve data",
    known_outliers = integer(0),
    reference = "robustbase package"
  ),
  diamonds = list(
    data = ggplot2::diamonds,
    formula = price ~ carat + table + depth + cut + color + clarity,
    features = c("carat", "table", "depth"),
    name = "Diamonds",
    description = "Attributes of over 50,000 diamonds",
    context = "Diamond price in relation to carat etc.",
    reference = "ggplot2 package"
  )
)
# Add microcredit
datasets <- datasets |> append(
  lapply(c("BIH", "MON", "ETH", "MEX", "MOR", "PHI", "IND"), \(site) {
    list(
      data = readRDS("../data/microcredit.rds")[[site]],
      formula = y ~ D,
      features = c("D"),
      name = paste0("Microcredit ", site),
      description = paste("Treatment effect of microcredit access in", site),
      context = paste0("Analysis for ", site, "; tests whether microcredit improves outcomes"),
      reference = "Meager (2019)"
    )
  }) |> setNames(
    paste0("microcredit_", c("BIH", "MON", "ETH", "MEX", "MOR", "PHI", "IND"))
  )
)
```

```{r functions, include=FALSE}
# Null-coalescing operator
`%||%` <- function(x, y) if (is.null(x)) y else x

summarize_result <- function(res) {
  values_p <- vapply(res[["miss_pos"]], \(l) l[["best_value"]], numeric(1L))
  values_n <- vapply(res[["miss_neg"]], \(l) l[["best_value"]], numeric(1L))

  k_n <- which.min(values_p)
  k_p <- which.max(values_n)

  coef_n <- values_p[[k_n]]
  coef_p <- values_n[[k_p]]
  delta_n <- coef_n - res$coef
  delta_p <- coef_p - res$coef

  sets_n <- lapply(res[["miss_pos"]], \(x) x[["best_S"]])
  sets_p <- lapply(res[["miss_neg"]], \(x) x[["best_S"]])
  breaks_n <- find_breaks(sets_n)
  breaks_p <- find_breaks(sets_p)
  jacc_n <- jaccard_consecutive(sets_n)
  jacc_p <- jaccard_consecutive(sets_p)

  overlap_p <- numeric(0L)
  overlap_n <- numeric(0L)
  if (!is.null(res[["greedy_pos"]]) && !is.null(res[["greedy_neg"]])) {
    overlap_p <- vapply(
      seq_len(res$K),
      \(k) {
        greedy_set <- res[["greedy_pos"]][["best_S"]][seq_len(k)]
        miss_set <- res[["miss_pos"]][[k]][["best_S"]]
        jaccard_index(greedy_set, miss_set)
},
      numeric(1L)
    )
    overlap_n <- vapply(
      seq_len(res$K),
      \(k) {
        greedy_set <- res[["greedy_neg"]][["best_S"]][seq_len(k)]
        miss_set <- res[["miss_neg"]][[k]][["best_S"]]
        jaccard_index(greedy_set, miss_set)
      },
      numeric(1L)
    )
  }

  iter_n <- vapply(res[["miss_pos"]], \(x) x[["iter"]], integer(1L))
  iter_p <- vapply(res[["miss_neg"]], \(x) x[["iter"]], integer(1L))

  mk_row <- function(dir, breaks, jacc, overlap, iter) {
    data.frame(
      Variable = res[["var_name"]],
      # Coef = res$coef,
      K = res[["K"]],
      Direction = dir,
      Breaks = length(breaks),
      `Mean Nesting` = if (length(jacc)) mean(jacc) else NA_real_,
      `Min Nesting`  = if (length(jacc)) min(jacc)  else NA_real_,
      `Mean Overlap` = if (length(overlap)) mean(overlap) else NA_real_,
      `Min Overlap`= if (length(overlap)) min(overlap)  else NA_real_,
      `Med Iters` = median(iter),
      `Max Iters` = max(iter)
    )
  }
  rbind(
    mk_row("Negative", breaks_n, jacc_n, overlap_n, iter_n),
    mk_row("Positive", breaks_p, jacc_p, overlap_p, iter_p)
  )
}

compute_results <- function(
  dataset, K_max = K_MAX, greedy = TRUE, start_warm = TRUE
) {
  results <- list()
  errors <- list()
  residualize <- ifelse(NROW(dataset$data) > 100L && NCOL(dataset$data) > 2L, update_plm, update_fwl)
  for (var in dataset$features) {
    res <- tryCatch({
      analyze_variable(
        dataset$data, dataset$formula, var_name = var,
        K = dataset$K_max %||% K_max,
        residualize = residualize,
        greedy = isTRUE(greedy), start_warm = isTRUE(start_warm)
      )
    }, error = function(e) {
      errors[[length(errors) + 1L]] <- data.frame(
        Dataset = dataset$name,
        Variable = var,
        Error = conditionMessage(e),
        check.names = FALSE
      )
      NULL
    })
    results[[var]] <- res
  }

  if (length(errors)) {
    attr(results, "errors") <- do.call(rbind, errors)
  }
  results
}

render_results <- function(dataset, results) {
  cat("\n\n## ", dataset$name, " {.tabset}\n\n", sep = "")
  cat("**Description:** ", dataset$description, "\n\n", sep = "")
  cat("**Context:** ", dataset$context, "\n\n", sep = "")
  cat("**Reference:** ", dataset$reference, "\n\n", sep = "")
  cat("**Formula:** ", deparse(dataset$formula) |> trimws(), collapse = " ", "\n\n", sep = "")
  cat("**Sample size:** n = ", nrow(dataset$data), "\n\n", sep = "")
  # cat("**Variables analyzed:** ", paste(dataset$features, collapse = ", "), "\n\n", sep = "")
  cat("---\n\n")

  sm_list <- lapply(dataset$features, \(var) {
    res <- results[[var]]
    if (is.null(res)) { return(NULL) }
    summarize_result(res)
  })
  sm <- Filter(Negate(is.null), sm_list)
  if (length(sm)) {
    tab <- do.call(rbind, sm) |> knitr::kable(
      format = "html", digits = 3, row.names = FALSE, caption = "Summary"
    )
    cat(tab, "\n\n")
  } else {
    cat("No results available for this dataset.\n\n")
  }

  # Return results for each variable
  for (var in dataset$features) {
    res <- results[[var]]

    if (is.null(res)) {
      cat("\n### ", var, " (Not Available)\n\n", sep = "")
      next
    }
    cat("\n### `", var, "`\n\n", sep = "")
    cat("**Full-sample coefficient:** ", formatC(res$coef), "\n\n", sep = "")

    # Summaries

    # Dinkelbach iterations
    iter_df <- rbind(
      data.frame(direction = "pos", iter = vapply(res[["miss_pos"]], \(l) l[["iter"]], integer(1L))),
      data.frame(direction = "neg", iter = vapply(res[["miss_neg"]], \(l) l[["iter"]], integer(1L)))
    )
    tab <- as.data.frame(table(iter_df$direction, iter_df$iter))
    names(tab) <- c("direction", "iterations", "count")
    tab <- tab[order(tab$direction, tab$iterations), ]
    tab$share <- tab$count / ave(tab$count, tab$direction, FUN = sum)
    cat("**Dinkelbach iterations (frequency):**\n\n")
    tab <- knitr::kable(tab,
      format = "html", digits = 3,
      row.names = FALSE, col.names = c("Direction", "Iterations", "Count", "Share")
    )
    cat(tab, "\n\n")

    # Coefficient trace plots
    cat("\n#### Coefficient Trace\n", sep = "")
    op <- par(mfrow = c(1, 1), mar = c(4, 4, 2, 1))
    plot_trace(res); cat("\n")

    cat("\n#### MISS vs. Greedy (Value, Set)\n\n", sep = "")
    has_greedy <- !is.null(res[["greedy_pos"]]) && !is.null(res[["greedy_neg"]])
    if(has_greedy) {
      op <- par(mfrow = c(2, 1), mar = c(4, 4, 2, 1))
      plot_error(res); cat("\n")
      plot_overlap(res); cat("\n")
      par(op)
    }

    # Jaccard plots
    cat("\n#### Set Stability (Jaccard, Nestedness)\n", sep = "")
    op <- par(mfrow = c(2, 1), mar = c(4, 4, 2, 1))
    plot_stability(res); cat("\n")
    plot_nestedness(res); cat("\n")
    par(op)

    # Dinkelbach plots
    # cat("\n#### Dinkelbach Iterations\n", sep = "")
    # op <- par(mfrow = c(1, 1), mar = c(4, 4, 2, 1))
    # plot_dinkelbach(res); cat("\n")
    # par(op)
  }

  invisible(results)
}
```

## Dataset Summary

```{r dataset-summary, echo=FALSE, cache=TRUE}
dataset_sm <- do.call(rbind, lapply(datasets, \(d) {
  data.frame(
    Name = d$name,
    n = NROW(d$data),
    Formula = deparse(d$formula) |> trimws() |> paste(collapse = " "),
    Variables = paste(d$features, collapse = ", ")
  )
}))
knitr::kable(dataset_sm, caption = "Dataset Overview", row.names = FALSE)
```


```{r execute, echo=FALSE, cache=TRUE, cache.lazy=FALSE, message=FALSE, warning=FALSE}
# name <- "housing_california"
# start <- Sys.time()
# # res <- datasets[[name]] |> compute_results(greedy = FALSE)
# res <- datasets[[name]] |> compute_results(greedy = TRUE)
# print(end <- Sys.time() - start)
# datasets[[name]] |> render_results(res)

# Precompute all results
dir.create("../outputs/analysis", showWarnings = FALSE, recursive = TRUE)

results <- list()
for(name in names(datasets)) {
  out_file <- file.path("../outputs/analysis", paste0(name, "-", K_MAX, "-greedy.rds"))
  if (file.exists(out_file)) {
    results[[name]] <- readRDS(out_file)
  } else {
    results[[name]] <- compute_results(datasets[[name]], greedy = TRUE)
    saveRDS(results[[name]], out_file)
  }
}
```

# Analysis

```{r analysis, echo=FALSE, cache=FALSE, results='asis'}
# Render summaries and plots
for(name in names(datasets))
  render_results(datasets[[name]], results[[name]])
```
